<?php

namespace App\Enums;

/**
 * Why a stock movement happened.
 *
 * Deliberately says nothing about direction — that lives on the signed
 * `quantity_delta`. A stock count that corrects downward and one that corrects
 * upward are both ADJUSTMENT, and reading direction off the type would make
 * that impossible.
 */
enum StockMovementType: string
{
    /** Stock that existed before the ledger did. Written once, by the backfill. */
    case OPENING_BALANCE = 'opening_balance';

    /** A delivery arriving at a branch. Creates a batch. */
    case STOCK_IN = 'stock_in';

    /** Automatic deduction from a completed appointment's treatment recipes. */
    case CONSUMPTION = 'consumption';

    /** Staff logging supplies used outside a recorded procedure. */
    case MANUAL_USAGE = 'manual_usage';

    /** A correction after a physical count. Signed either way. */
    case ADJUSTMENT = 'adjustment';

    case TRANSFER_IN = 'transfer_in';
    case TRANSFER_OUT = 'transfer_out';

    /** Expired stock written off the shelf. */
    case EXPIRED_WRITEOFF = 'expired_writeoff';

    public function label(): string
    {
        return match ($this) {
            self::OPENING_BALANCE  => 'Opening balance',
            self::STOCK_IN         => 'Stock in',
            self::CONSUMPTION      => 'Used in treatment',
            self::MANUAL_USAGE     => 'Manual usage',
            self::ADJUSTMENT       => 'Adjustment',
            self::TRANSFER_IN      => 'Transfer in',
            self::TRANSFER_OUT     => 'Transfer out',
            self::EXPIRED_WRITEOFF => 'Expired write-off',
        };
    }

    /**
     * Types where the number alone does not explain itself.
     *
     * An adjustment or a write-off is someone asserting that reality disagrees
     * with the ledger, which is exactly the case a reader will want explained
     * later. A delivery or a treatment deduction carries its own story.
     */
    public function requiresReason(): bool
    {
        return match ($this) {
            self::ADJUSTMENT, self::EXPIRED_WRITEOFF => true,
            default => false,
        };
    }

    /** Generated by the system rather than typed by a person. */
    public function isAutomatic(): bool
    {
        return $this === self::CONSUMPTION || $this === self::OPENING_BALANCE;
    }

    /** @return list<string> */
    public static function values(): array
    {
        return array_map(fn (self $case): string => $case->value, self::cases());
    }
}
